### ISSUE TITLE
Generate tests for given time

### ISSUE THREAD

**Issue by dantheuber** [mcandre/node-quickcheck#8]
Learned about quickcheck from the following video: https://www.youtube.com/watch?v=AfaNEebCDos

During this, a method is used to indicate that quickcheck should generate tests for a given amount of time and run as many tests as it can generate for that time. It appears that this implementation has an arbitrary length of 100 in the `forAll` method.

Is this timed functionality already built in? The documentation for this only links to others examples of using the tests and none of them have a timed test, so I am not sure.

**Comment by mcandre** [comment]
Submit a PR.
