### ISSUE TITLE
Homepage link is broken

### ISSUE THREAD

**Issue by lukehesluke** [mcandre/node-quickcheck#9]
When I click on the "HOMEPAGE" link, http://www.yellosoft.us/quickcheck, I get redirected to a web page like http://ww1.yellosoft.us/?sub1=a3d26a68-5b2c-11e7-aba5-49e9ac01696d which sometimes spouts ads

**Comment by mcandre** [comment]
Correct, I took down my yellosoft site a few years back. There is no longer a central yellosoft quickcheck summary website collating the shallow ports I published. I can update the GitHub repo homepage to point to itself, or even just remove the link altogether.

**Comment by mattly** [comment]
Can you remove the link? It leads to a site trying to get you to install a "flash player update"
